### ISSUE TITLE
Related Posts always show the latest three articles 

### ISSUE THREAD

**Issue by xmuplus** [Stanko/Stanko.github.io#18]
Sir, your new jekyll blog looks great! 

A small question is that in the previous blog that based on Lanyon and this new blog, `related posts` always show the newest three articles in Septhember.

**Comment by Stanko** [comment]
Yeah, that's jekyll's default behavior, it should be called "Latest posts". I plan to implement real related posts, here are few links I found.

https://github.com/jumanji27/related-posts-jekyll-plugin
https://github.com/alfanick/jekyll-related-posts/
https://anmonteiro.com/2015/08/jekyll-related-posts-revamped/
http://stackoverflow.com/questions/25348389/jekyll-and-liquid-show-related-posts-by-amount-of-equal-tags-2

**Comment by xmuplus** [comment]
Thanks! Sir.

The third article you linked also shows the "Latest posts". The forth approach contain "Tags". Can you modify the `related posts` code without using plugin in your leisure? Thanks!

**Comment by Stanko** [comment]
Well, you can using tags. Any more complicated approach needs a plugin written in ruby. GitHub pages do not support custom plugins (check the first note here https://jekyllrb.com/docs/plugins/). 

So to achieve it, you'll need to use the code from the third of the fourth link.

I will close this, as this not really an issue with my code.
