### ISSUE TITLE
[Question] Asking for permission

### ISSUE THREAD

**Issue by manashmndl** [Stanko/Stanko.github.io#41]
I really really loved your personal website. I'd be grateful if I could get your permission on using your theme on my personal blog too. You'll be credited properly. 

Thanks in advance!

**Comment by Stanko** [comment]
Hello Manash,
I would prefer to keep that theme exclusive to my website. For two reasons, to make my blog recognizable, and because I hired a design agency to do it.

I'll update the readme for licensing. Feel free to use the jekyl code, but please don't use design.

Thanks for understanging!

**Comment by manashmndl** [comment]
Thanks for the permission for using the code! I'll modify the design. Thank you again 👍

**Comment by Stanko** [comment]
@manashmndl I can see that you used exactly the same design here http://www.manash.me/ .

Can you please remove it and use other theme? I already told you that you can't reuse it, and licensing is pretty clear - you can use only Jekyll code if you ask for permission.

Design is copyrighted, all rights reserved.

Thank you!

**Comment by manashmndl** [comment]
I will surely modify the design when I get time. I was experimenting with the code. Sorry and thanks.

**Comment by Stanko** [comment]
@manashmndl I can't be more clear - you are not allowed to use the design, do not modify it, use something else.

Thank you!

**Comment by manashmndl** [comment]
No no, I won't use the design, I will use the code only.

**Comment by Stanko** [comment]
Thank you!

**Comment by manashmndl** [comment]
I'll put down the theme as soon as possible. Thank you for understanding.
