### ISSUE TITLE
Three.js Extrude SVG path demo is clipped

### ISSUE THREAD

**Issue by corysimmons** [Stanko/Stanko.github.io#452]
![image](https://github.com/Stanko/Stanko.github.io/assets/224636/5f5ce9a7-a868-447b-a11f-2fff852b3e55)

https://codepen.io/stanko/pen/gObMepb

I'm not really sure what's going on here. Thanks for the write-up though!

**Comment by Stanko** [comment]
Hey, thanks for pointing it out. It is an old one, I’ll check it out.
Cheers! :)

**Comment by Stanko** [comment]
They say better late than never 😅 fixed it! Thank you for reporting it!
