### ISSUE TITLE
RSS is invalid

### ISSUE THREAD

**Issue by simevidas** [Stanko/Stanko.github.io#453]
https://muffinman.io/atom.xml

![Screenshot 2024-01-02 at 00 53 31(1)](https://github.com/Stanko/Stanko.github.io/assets/716405/7a638e25-6372-4c42-9656-5f94732c22cc)

**Comment by Stanko** [comment]
Ah, I broke it again... Thank you for reporting, I'll patch it, but I really need to add a validation in a git hook.

Cheers!

**Comment by Stanko** [comment]
It should be fixed now, thanks again! If you have a suggestion for a CLI validation tool, I would really appreciate it (I couldn't find one that is maintained).
